#!/bin/bash
# Don't pass in args so it never shows up in ps
read token

# gpg-preset-passphrase is often in /usr/libexec or /usr/lib/gnupg
preset=/usr/lib/gnupg/gpg-preset-passphrase


# Before the GPG_PRESETS
HEAD=`sed '/BEGIN_GPG_PRESETS/q' /home/iocanel/.zlogin`

# After the GPG_PRESETS
TAIL=`sed -n '/END_GPG_PRESETS/,$ p' /home/iocanel/.zlogin`

cat >   /home/iocanel/.zlogin <<< "$HEAD"

keygrips=($(gpg -K --fingerprint --with-keygrip | grep Keygrip | awk -F " = " '{print $2}'))

# Preset each fingerprint
for keygrip in "${keygrips[@]}"
do
    PRESET_CMD="$preset -c \"$keygrip\"  <<< \"$token\""
    cat >> /home/iocanel/.zlogin <<< "$PRESET_CMD"
done

cat >> /home/iocanel/.zlogin <<< "$TAIL"
