import = ["/home/iocanel/.config/alacritty/themes/current-theme.toml"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light Italic"


[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B\r"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mods = "None"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mods = "None"

[[mouse.bindings]]
action = "Paste"
mouse = "Middle"
