#!/bin/sh

# Stow common
stow --no-folding --adopt -t alacritty
stow --no-folding --adopt -t clipmenu
stow --no-folding --adopt -t chatgpt
stow --no-folding --adopt -t flameshot
stow --no-folding --adopt -t docker
stow --no-folding --adopt -t emacs
stow --no-folding --adopt -t emacs-doom
stow --no-folding --adopt -t gnupg
stow --no-folding --adopt -t gmail
stow --no-folding --adopt -t outlook
stow --no-folding --adopt -t htop
stow --no-folding --adopt -t kitty
stow --no-folding --adopt -t kubemenu
stow --no-folding --adopt -t maven
stow --no-folding --adopt -t mbsync
stow --no-folding --adopt -t monitor-mgmt
stow --no-folding --adopt -t msmtp
stow --no-folding --adopt -t mutt
stow --no-folding --adopt -t neovim
stow --no-folding --adopt -t network-manager
stow --no-folding --adopt -t pulse
stow --no-folding --adopt -t qutebrowser
stow --no-folding --adopt -t ranger
stow --no-folding --adopt -t vdirsyncer
stow --no-folding --adopt -t wacom
stow --no-folding --adopt -t zsh
stow --no-folding --adopt -t nix-sdk
stow --no-folding --adopt -t java-utils
stow --no-folding --adopt -t utils-work
stow --no-folding --adopt -t tmux
stow --no-folding --adopt -t theme-manager
stow --no-folding --adopt -t k9s
stow --no-folding --adopt -t ideavim
stow --no-folding --adopt -t home-manager
stow --no-folding --adopt -t nyxt
stow --no-folding --adopt -t yapt
stow --no-folding --adopt -t zulip

# stow wayland
pushd wayland
./stowall
popd
