#!/bin/zsh

export MAGICK_OCL_DEVICE=OFF 

# Attempt to shutdown gracefully
emacsclient -e "(kill-emacs)"

# Forcefully kill daemon if still alive.
PID=`ps -aef | grep emacs | grep daemon | awk -F " " '{print $2}'`
kill -9 $PID

source ~/.zshenv
/usr/bin/emacs --daemon

# Send notification and switch to namespace
notify-send -a "Emacs" -u "normal" -i /usr/share/icons/hicolor/48x48/apps/emacs.png "Restarted" "Emacs daemon has been restarted"

