#!/bin/bash

#For GPG
GNUPGHOME=~/.gnupg
GPG_TTY=$(tty)
export GPG_TTY

cleanup() {
  if [ -f $HOME/.config/weechat/irc.conf ]; then
    rm $HOME/.config/weechat/irc.conf
  fi

  if [ -f $HOME/.config/weechat/plugins.conf ]; then
    rm $HOME/.config/weechat/plugins.conf
  fi
}

cleanup

trap "cleanup" EXIT

IRC_NICKSERV_PASS=`pass show irc/freenode/nicksrv`
MATRIX_PASSWORD=`pass show matrix/iocanel/password`
sed -e "s/\${sec.data.freenode}/$IRC_NICKSERV_PASS/g" $HOME/.config/weechat/password-store/irc.conf > $HOME/.config/weechat/irc.conf 
sed -e "s/\${sec.data.matrix}/$MATRIX_PASSWORD/g" $HOME/.config/weechat/password-store/plugins.conf > $HOME/.config/weechat/plugins.conf 
/usr/bin/weechat -d $HOME/.config/weechat
