#!/bin/sh

#
# Grabs the selected text and apply it to kubernetes using `kubectl`.
# 
# OS: Linux
# Requirements: xsel, notify-send
#
# Bind this to a key of your choice. 
# Example (i3):
# bindsym $mod+Shift+a exec ~/scripts/k8s/kube-apply-from-clipboard


set +e

TEMP_FILE=$(mktemp /tmp/kubernetes.XXXXXX)
xsel -p -o -n > $TEMP_FILE
KUBE_OUT=`kubectl apply -f $TEMP_FILE`
if [ $? -eq 0 ]; then
 notify-send -u normal -a "kubectl" "Succuess: $KUBE_OUT"
else
 notify-send -u critical -a "kubectl" "Failed: $KUBE_OUT"
fi
