#!/bin/bash

TUN_MODULE=`sudo lsmod | grep -sw tun`
DEFAULT_NET=`sudo virsh net-list | grep active | grep default`
DOCKER_MACHINES_NET=`sudo virsh net-list | grep active | grep docker-machines`

DEFAULT_MEMORY=8192
DEFAULT_NAMESPACE=iocanel

if [ -z "$1" ]; then
    MEMORY=$DEFAULT_MEMORY
else
    MEMORY=$1
fi

if [ -z "$TUN_MODULE" ]; then
   echo "Installing tun module..."
   sudo modprobe tun
fi

if [ -z "$DEFAULT_NET" ];then
	echo "Creating net default..."
	sudo virsh net-start default
fi

if [ -z "$DOCKER_MACHINES_NET" ];then
	echo "Creating net docker-machines..."
	sudo virsh net-start docker-machines
fi


# make sure the profile is set correctly
minishift profile set knative

# Pinning to the right needed OpenShift version in this case v3.11.0
minishift config set openshift-version v3.11.0

# memory for the vm
minishift config set memory 16GB

# the vCpus for the vm
minishift config set cpus 4

# extra disk size for the vm
minishift config set disk-size 80g

# caching the images that will be downloaded during app deployments
minishift config set image-caching true

# Add new user called admin with password with role cluster-admin
minishift addons enable admin-user

# Allow the containers to be run with uid 0
minishift addons enable anyuid

# Start minishift
minishift start --vm-driver=kvm --profile=knative -v 8
RESULT=$?

eval $(minishift docker-env) && eval $(minishift oc-env)
