[colors.primary]
background = '0xffffff'
foreground = '0x24292f'

[colors.normal]
black = '0x24292e'
red = '0xd73a49'
green = '0x28a745'
yellow = '0xdbab09'
blue = '0x0366d6'
magenta = '0x5a32a3'
cyan = '0x0598bc'
white = '0x6a737d'
