{ config, lib, pkgs, osConfig ? null, ... }:

with lib;

let
  cfg = config.custom.display-manager;
  # Auto-detect backend from NixOS config if available, otherwise use home-manager setting
  detectedBackend = if osConfig != null && osConfig ? custom.display-manager.backend 
    then osConfig.custom.display-manager.backend 
    else cfg.backend;
in
{
  imports = [
    ./wayland.nix
    ./xorg.nix
  ];

  options.custom.display-manager = {
    enable = mkEnableOption "Enable custom display manager configuration";
    
    backend = mkOption {
      type = types.enum [ "wayland" "xorg" ];
      default = "wayland";
      description = "Display backend to use (wayland/sway or xorg/i3). Auto-detected from NixOS config if available.";
    };
  };

  config = mkIf cfg.enable {
    # Enable the selected backend (auto-detected from NixOS or manual setting)
    wayland.enable = detectedBackend == "wayland";
    xorg.enable = detectedBackend == "xorg";
    
    # Show which backend was selected
    home.file.".config/display-backend".text = ''
      # Auto-generated by home-manager display-manager
      # Backend: ${detectedBackend}
      # Source: ${if osConfig != null && osConfig ? custom.display-manager.backend then "NixOS config" else "home-manager config"}
    '';
  };
}
