#!/bin/bash

#Delete local openshift cluster
pushd ~
oc cluster down
sudo rm -rf openshift.local.clusterup 
oc cluster up
oc login -u system:admin
oc cluster add service-catalog
oc cluster add template-service-broker
popd

# Kill Java
pkill java

# Cleanup Projects
rm -rf ~/f2f-demo

# Cleanup backups
rm ~/.emacs.d/backups/\!home\!iocanel\!f2f-demo*

# Cleanup workspace 
rm -rf ~/.emacs.d/workspace/*
