#!/bin/bash

# An docker wrapper that sends a notification when the build is done.
# Just throught it under $HOME/bin and create and alias:
# alias docker=$HOME/bin/dockernotify
#
# Requirements: notify-send & xml2
#

TITLE="Docker"
DOCKER=`type -p docker | cut -d " " -f3`
DESCRIPTION=""
if [ "$1" == build ]; then
	shift 1
	while getopts ":t:" opt; do
		case $opt in
			t)
				DESCRIPTION="\n$OPTARG"
				;;
			:)
				echo "Option -$OPTARG requires an argument." >&2
				;; 
		esac
	done
else 
	eval $DOCKER $*
	RESULT=$?
	exit $RESULT
fi

eval $DOCKER build $*
RESULT=$?

if [ $RESULT == 0 ]; then
	ERGENCY="normal"
	STATUS="Build Succeeded"
else
	ERGENCY="critical"
	STATUS="Build Failed"
fi

notify-send -a "$TITLE" -u "$ERGENCY" "$STATUS" "$DESCRIPTION"
