#!/bin/bash

# An mvn wrapper that sends a notification when the build is done.
# Just throught it under $HOME/bin and create and alias:
# alias mvn=$HOME/bin/mvnnotify
#
# Requirements: notify-send & xml2
#
MVN=`type -p mvn | cut -d " " -f3`
eval $MVN $*

RESULT=$?
TITLE="Maven"

#Don't report anything if its an `mvn -verison`
if [ "$1" == "-version" ];then
	return result
fi

if [ -f pom.xml ]; then
   NAME=`xml2 < pom.xml  | grep /project/name= | sed 's/.*=//'`
   if [ -z "$NAME" ]; then
   	NAME=`xml2 < pom.xml  | grep /project/artifactId= | sed 's/.*=//'`
   fi
   VERSION=`xml2 < pom.xml  | grep /project/version= | sed 's/.*=//'`
   DESCRIPTION="\n$NAME \n$VERSION"
else
	DESCRIPTION=""
fi

if [ $RESULT == 0 ]; then
	ERGENCY="normal"
	STATUS="Build Succeeded"
else
	ERGENCY="critical"
	STATUS="Build Failed"
fi

notify-send -a "$TITLE" -u "$ERGENCY" "$STATUS" "$DESCRIPTION"
