#!/bin/sh

stow --no-folding --adopt -t ~ i3
stow --no-folding --adopt -t ~ dunst
stow --no-folding --adopt -t ~ rofi
stow --no-folding --adopt -t ~ x-resources
stow --no-folding --adopt -t ~ conky
stow --no-folding --adopt -t ~ screenlock