SCRIPTS_HOME=$HOME/scripts

export PATH=${SCRIPTS_HOME}:${SCRIPTS_HOME}/dev:${SCRIPTS_HOME}/install:${SCRIPTS_HOME}/k8s:${SCRIPTS_HOME}/notify:${SCRIPTS_HOME}/sound:${SCRIPTS_HOME}/util:${SCRIPTS_HOME}/wm:${SCRIPTS_HOME}/work:${SCRIPTS_HOME}/wrap:${PATH}
